#!/usr/bin/env bash
# This script configures /etc/hosts to redirect localhost and facebook.com

# Change the loopback address for localhost from 127.0.0.1 to 127.0.0.2
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

# Add a specific entry to redirect facebook.com to Google's DNS IP
echo "8.8.8.8 facebook.com" >> /etc/hosts
